language: android
jdk: oraclejdk8
sudo: false

env:
  - TEST_SUITE=units
  - TEST_SUITE=integration

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.3
    - android-24
    - sys-img-armeabi-v7a-android-24
    - extra-android-m2repository
    - extra-google-m2repository

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &

script:
  - ./gradlew check -PdisablePreDex --continue --stacktrace
    - android-wait-for-emulator
    - adb devices
    - adb shell input keyevent 82 &
    - ./gradlew connectedAndroidTest -PdisablePreDex --continue --stacktrace
